In [1]:
import numpy as np

In [4]:
arreglo_int = np.random.randint(1, 100, (5,3))

print(arreglo_int)

[[43 86 54]
 [58 37 71]
 [66 29  1]
 [28 94 47]
 [76  6 17]]


In [6]:
suma_total = np.sum(arreglo_int)
print(suma_total)

713


In [8]:
prom_columnas = np.mean(arreglo_int, axis=0)
print(prom_columnas)

[54.2 50.4 38. ]


In [9]:
matriz = np.random.randint(0,10,(10,10))
print(matriz)

[[8 9 2 7 9 0 2 5 6 0]
 [9 0 7 2 5 1 3 4 2 5]
 [2 6 9 7 9 6 5 0 3 1]
 [8 5 9 8 2 8 4 0 5 5]
 [3 6 6 3 3 9 2 3 1 2]
 [0 3 8 0 3 4 2 0 5 6]
 [8 3 7 8 4 0 0 6 6 7]
 [0 3 2 1 7 1 1 7 9 9]
 [0 1 2 1 9 5 9 6 7 7]
 [8 6 9 5 4 9 5 6 9 5]]


In [ ]:
matriz[matriz < 5] = -1
print(matriz)



[[ 8  9 -1  7  9 -1 -1  5  6 -1]
 [ 9 -1  7 -1  5 -1 -1 -1 -1  5]
 [-1  6  9  7  9  6  5 -1 -1 -1]
 [ 8  5  9  8 -1  8 -1 -1  5  5]
 [-1  6  6 -1 -1  9 -1 -1 -1 -1]
 [-1 -1  8 -1 -1 -1 -1 -1  5  6]
 [ 8 -1  7  8 -1 -1 -1  6  6  7]
 [-1 -1 -1 -1  7 -1 -1  7  9  9]
 [-1 -1 -1 -1  9  5  9  6  7  7]
 [ 8  6  9  5 -1  9  5  6  9  5]]
True


In [ ]:
import cv2


# Leer la imagen
imagen = cv2.imread("logo2.png")

# Verificar si la imagen se cargó correctamente
if imagen is None:
    print("Error: No se pudo cargar la imagen. Verifica la ruta.")
else:
    print("Imagen cargada correctamente.")

    # Mostrar shape, mínimo, máximo y promedio de cada canal
    print("Shape:", imagen.shape)
    print("Mínimo por canal:", imagen.min(axis=(0, 1)))
    print("Máximo por canal:", imagen.max(axis=(0, 1)))
    print("Promedio por canal:", imagen.mean(axis=(0, 1)))

    # Mostrar la imagen en una ventana
    cv2.imshow("Imagen", imagen)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


Imagen cargada correctamente.
Shape: (768, 1024, 3)
Mínimo por canal: [27 29 29]
Máximo por canal: [255 255 255]
Promedio por canal: [203.67577616 236.65513357 240.80700811]
